# A dockerfile must always start by importing the base image.
# We use the keyword 'FROM' to do that.
FROM python:latest

# Copy the python script into the image (root folder).
COPY main.py /

# Command to run when the container starts.
CMD [ "python", "./main.py" ]
